package org.jakarta.sso.keycloak;

import org.jakarta.sso.abstracttests.AbstractSSOTest;
import org.jakarta.sso.token.auth.AbstractSSOAuth;
import org.jakarta.sso.token.auth.SSOTokenAndCerts;

public class KeycloakTestingRealmSSOTest extends AbstractSSOTest {

    private KeyCloakSSOAndCerts keyCloakSSOAndCerts = new KeyCloakSSOAndCerts();

    @Override
    protected SSOTokenAndCerts getSsoTokenAndCerts() {
        return keyCloakSSOAndCerts;
    }

    @Override
    protected AbstractSSOAuth getSSOAuth() {
        return new KeyCloakSSOAuth(keyCloakSSOAndCerts);
    }

    @Override
    protected String getToken() {
        return "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJET1VtVXU1UEpId25KMEp1bmdnN3prMjFkQkoydXM0eW9uUU1oZmZjM3U4In0.eyJleHAiOjE3NDIzMDI2MzMsImlhdCI6MTc0MjMwMjMzMywianRpIjoiOGIwYjQ5YWItNDhmOS00NDBjLTg0MDAtMTVkNDViOTkxZDczIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0aW5nIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImVmMDgwNWVhLWU1YTktNDY2MS1hYWRlLTU0Mjg2NzY3ZTQ3MyIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3QtYXBwIiwic2lkIjoiMjRmN2QzMTYtMmQ4Ny00N2M0LTgyMGYtZTA5YWYxMmI5MjkzIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy10ZXN0aW5nIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImggaCIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QtdXNlciIsImdpdmVuX25hbWUiOiJoIiwiZmFtaWx5X25hbWUiOiJoIiwiZW1haWwiOiJ3cUBqbWFpbC5jb20ifQ.cjSRZiBhfJXzUnrfQXqvZUOrgo9tQGir82t78ZYHu_IrAIS-HlsJxQkaRz-pVjVDyBxMyGqy-MEoEadL8sqaga-gb2LFkrMxemaFCcCFBkmyiwX3Z10d5Cju73Fyfu2NOVIDYklcBB2zLi1dCvPRnblXOwB0of3IE_BBcQLG0NdDDd1kE9Qfiygz9qNkT1kEMNxH7wVTpyTh6LsNxsjFTh3o6thpBuhMyMYC-mWMTW9tpV3XplJ48YN1gNcVYGubJHXbG0PsMgJxZbGqEARr1r67HqEXqGOX4cbv1Sy6PRa4spO7xd5OPT7VfeqP-RDII-3_pJOSVnI9n9Xh0RakCA";
    }

    @Override
    protected String getDiffKidToken() {
        return "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJsWTFUbUltQzRheDEtbE9mT2NuTGZZVGV0SkxZcVl0dmh0T1JnZFl1RlcwIn0.eyJleHAiOjE3NDIzMDI2ODYsImlhdCI6MTc0MjMwMjM4NiwianRpIjoiNWJmNDNhOTItYjY3ZC00M2Y4LTlhY2MtMjFiOGVhYWNmZGNhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0aW5nLTIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMTg5ODhiYmQtNzM1Ni00OGViLTk0YjgtMjAwYTEwMGU3MmJlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGVzdC1hcHAiLCJzaWQiOiJlNGJkYjNmZS1lNTc5LTQ3MzEtODk3YS1kMzNjOTA1MmM0N2EiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtdGVzdGluZy0yIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJqIGoiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0LXVzZXIiLCJnaXZlbl9uYW1lIjoiaiIsImZhbWlseV9uYW1lIjoiaiIsImVtYWlsIjoid3FAam1haWwuY29tIn0.sQ5KGKl2xQz_qLZ3lkKEpEQxenqj4GZMglyN6UP616Hz4gqz8FxpSERN9PBh16bu6bBM5Bx0WdShYaPgg78LJhrdQfFmHWQm6nJeIvVeW4jdTudYhPeAjGv8zfhdjS2NCKy1zZHLeMyUU9KniLugCsB-sekpKwH9BVqd78KnIS7op722lGbl9fwukUtBxLsJP0mtKKiNzvPNpCPRyUpFYXx7uCD7qmSpwwfeLzn3nKbfDF8L6Y8Kudb3IzxwhqjZTm5pETHAo1hnVAfPBa5Qoj3oR1NJMZkh5WVghEizCX4nXWRyrWfpWhE-rRFtX-b4PHocWel2rgO1cfrnFX4B7Q";
    }

    @Override
    protected String getEmptyKidToken() {
        return "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3NDIyODk5NjYsImV4cCI6MTc3MzgyNTk2NiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.QoM49yoVbAhcIjoP5j25HOG8cBR_FWiRiAuPyO7re5o";
    }

    @Override
    protected String getTestKid() {
        return "DOUmUu5PJHwnJ0Jungg7zk21dBJ2us4yonQMhffc3u8";
    }
}
